GET http://localhost:3000/todos

###

POST http://localhost:3000/todo/new
Content-Type: application/json

{
    "text" : "Pizza"
}

###

DELETE http://localhost:3000/todo/delete/64ca6ec463a034e965196981


###

PUT http://localhost:3000/todo/complete/64ca6ee663a034e965196984